### ISSUE TITLE
Missing app modules

### ISSUE THREAD

**Issue by fedekunze** [cosmos/peggy#108]
I noticed some modules are missing on the app.go. I wanted to start a discussion about the available modules that the peg zone should or must have.

Must have:

- `x/evidence`: evidence handling was migrated from x/slashing to the new evidence module 
- `x/slashing`: for downtime and double sign slashing
- `x/upgrade`: reduces the upgrading time from software updates (i.e new version releases) to only a few minutes. Integrates upgrade proposals to ease the coordination process on versioning, exact time/height of the upgrade.
- `x/gov`: for param change, text, community spend and upgrade proposals, etc.
- `x/distribution`: in protocol staking reward and fee distribution mechanism for validators and delegators. 
- `x/crisis`: submit a tx to halt the chain in case an invariant check has been found.
- `x/mint`: Inflation rates for the coins (eg: staking coin). 

Other modules (TBD): 

- `x/ibc`: IBC protocol implementation

**Comment by jackzampolin** [comment]
@fedekunze great point. I think we should add these in!
