### ISSUE TITLE
Comments and code are not unified in Oracle.sol 

### ISSUE THREAD

**Issue by YingQm** [cosmos/peggy#155]
The comment on line 198 in the file is 
`The hardcoded threshold is (Combined signed power * 2) >= (Total power * 3).` 

but the code on line 225 is 
`uint256 weightedSignedPower = signedPower.mul(3);
        uint256 weightedTotalPower = totalPower.mul(2);`, 

they are not uniform.

**Comment by denalimarsh** [comment]
Fixed in https://github.com/cosmos/peggy/pull/160
