### ISSUE TITLE
Bad Status Error while starting the Relayer service on ropsten Ethereum blockchain

### ISSUE THREAD

**Issue by osiz-blockchainapp** [cosmos/peggy#156]
while starting the Relayer service on ropsten Ethereum blockchain getting following below error but the same setup works fine in local ethereum blockchain.

`ebrelayer init ethereum wss://ropsten.infura.io/ws 0x0E081DbCA84539F45780A
0A24E3dd24753f65C09 validator --chain-id=peggy
ERROR: bad status
`   
this command also throws the same error
`ebrelayer init ethereum wss://ropsten.infura.io/ws 0x0E081DbCA84539F45780A
0A24E3dd24753f65C09 validator --make-claims=false --chain-id=peggy
` 
How could i resolve this error?

**Comment by VoroshilovMax** [comment]
Try 
`ebrelayer init tcp://localhost:26657 wss://ropsten.infura.io/ws/v3/project_id [cosmos_wallet] validator --chain-id=peggy `
it work for me fine!
