### ISSUE TITLE
Use `secp256k1` signatures and relay commit signatures to Ethereum directly

### ISSUE THREAD

**Issue by sorawit** [cosmos/peggy#165]
Tendermint supports `secp256k1` natively, although you need to set that in genesis.json to force all validators to use that signature scheme. 

```
{
  "genesis_time": ...,
  "chain_id": ...,
  "consensus_params": {
    ...
    "validator": {
      "pub_key_types": [
        "secp256k1"
      ]
    }
  },
  ...
}
```

And you also need override `ebd init` to generate `secp256k` for validators in `priv_validator_key.json`. Here is some [example code](https://github.com/bandprotocol/bandchain/blob/cbb98ab173a5c6e94b1ef50f2fcafa45db18c4d3/chain/cmd/bandd/init.go#L65) to do that.

Once that's done, the precommit signatures produced in Tendermint will be verifiable cheaply on Ethereum and you can relay that directly with app state hash and a Merkle proof certifying that the message is part of the app hash. This will eliminate the need of `ebrelayer` completely.

For code that can be used to verify validator signatures on Ethereum, you can look at our bridge [implementation](https://github.com/bandprotocol/bandchain/blob/cbb98ab173a5c6e94b1ef50f2fcafa45db18c4d3/bridges/evm/contracts/Bridge.sol#L68) for Solidity reference. And this is a very messy code that shows how to get data to send to the contract, though very specific to our usecase and Cosmos-SDK 0.37.*: [here](https://github.com/bandprotocol/bandchain/blob/cbb98ab173a5c6e94b1ef50f2fcafa45db18c4d3/chain/client/proof.go). What are you guy thoughts / opinions on this? Happy to discuss more.

**Comment by denalimarsh** [comment]
Great issue, thank you for the example code @sorawit. This has the potential to remove the second layer of oracles. Given the similarity, I'm interested in what some of the guys familiar with IBC think about this proposal @fedekunze @jackzampolin @cwgoes
