### ISSUE TITLE
Implement pegzone component

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/peggy#17]
The pegzone ties all other components (Witness, Relayer and Signer) together. It defines the format for WitnessTx, WithdrawTx, SignTx and SendTx.

The WitnessTx is send by the Witness component. It results in the pegzone writing the event (usually a deposit into the Ethereum smart contract) into its state. There is aggregates all WitnessTxs for a given event and credits a user account once >2/3 of validators have witnessed an event.
```golang
type WitnessTx struct {
    ethEvent EthEvent // encapsulates amount, token and destination address
    signature Signature // has to be a signature from a key in the validator set
}

type EthEvent struct {
    destination []byte // pegzone address
    coin Coin // contains denom and amount of the token to be send
```

The WithdrawTx is sent by a user to send money from the pegzone to Ethereum. The pegzone checks whether the user has the correct token balances and then deducts them from the user account.
```golang
type WithdrawTx struct {
    destination []byte // Ethereum address of destinatary
    coin Coin // contains denom and amount of the token to be send
    signature Signature // a signature that authorises this transaction
}

type WithdrawData struct {
     SignedWithdraw []SignTx	 // Accumulates `SignTx`s until it reaches +2/3 of total power
}
```

The SignTx is sent by the Signer component. 
```golang
type SignTx struct {
    signatureBytes []bytes // signature bytes over the concatenation of the top three fields of ReedemTx
    signature Signature // signature that authorises this transaction is coming from a validator
}
```

@ethanfrey @spacejam @mossid @sunnya97 @fedekunze 
The SendTx is used to send tokens between user account on the pegzone.

**Comment by adrianbrink** [comment]
This is the application that is written on top of the cosmos-sdk. It is the first major piece of software that is written from scratch just on the cosmos-sdk and as such provides an ideal testing ground for the ergonomics of the sdk. Everything we learn here, we need to feed back into the cosmos-sdk in order to improve it.

The overall design is simple. All transactions are defined in types/transactions.go. 
The three main components are `WitnessTxMapper`, `WithdrawTxMapper` and the `bank module`.

`WitnessTxMapper` stores a mapping from `WitnessTxHash -> WitnessData`. The first `WitnessTx` initializes that mapping and subsequent `WitnessTx` transactions will append information to the respective `WitnessData`. Every `EndBlock` we check whether >2/3 of validators have witnessed a `Lock Event` and if so, we credit that amount.

`WithdrawTxMapper` stores a mapping from `WithdrawTxHash -> WithdrawData`. It works like the `WitnessTxMapper` except that it is used to accumlate `SignTx` transactions so that a `Relayer` can eventually take them and submit them to `Peggy SC`.

The `bank module` keeps track of user balances and adds the ability to send tokens between accounts.

At the moment the `Withdraw` and `Witness` are just placed in the global state. There might be a point to have them as separate modules and move them into `x/withdraw` and `x/witness`. 

Currently, this PR does not compile. It adds the overall skeleton and architecture and now we have to go through it and fix all the broken parts. Ideally, we should start with the types and work our way up. In order to do this, we have to figure out how to best test modules in isolation and generally how to test applications without having to run against a live instance of TMC.

Let's use this opportunity to test how easy it is to build on top of the cosmos-sdk and how we can smooth out the rough edges.


This PR is not designed to build any of the other processes, such as `Signer`, `Witness`, or `Relayer`. Those will be added in different PRs.


@mossid @sunnya97 @zmanian : Once #27 is merged, let's focus on building the peg zone. #27 includes all the needed functionality for the MVP on `Ethereum SC`. After the peg zone application is merged, we can move on to the `Witness`, then to the `Signer` and finally, we can implement the `Relayer`. If we see that it is infeasible to work with 4 people on the same code, then we can parallelise the development and build the `Witness` and the `PeggyApp` at the same time.

Please let me know if you have suggestions for this development plan. Any two people can merge a PR. So, you need one other person (from us 4) to review and approve the PR and you are free to merge it. This applies to every part of `cosmos/peggy`.

**Comment by fedekunze** [comment]
@adrianbrink Shouldn't `RedeemTx` be instead `WithdrawTx` ?

**Comment by adrianbrink** [comment]
Yes

**Comment by fedekunze** [comment]
outdated
