### ISSUE TITLE
Implement Ethereum pegzone contract

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/peggy#19]
The Ethereum pegzone contract has a function that takes `amount int64, denom string, signatures []signatures`. Signatures is a solidity struct that encapsulates the components of a signature. It is used by the smart contract to authenticate the rest of the data.

The smart contract hashes amount and denom and checks whether all signatures come from a validator and wether the sum of signatures accounts for >2/3 of the voting power.

```golang
type Signatures struct {
    ...
}
```

@mossid @fedekunze @sunnya97

**Comment by 0v1se** [comment]
In the Valset contract signatures of validators are checked (for 2/3 majority)

Do you have any mechanism for bad behaviour of validators for this action?
For example, some of the validators can sign unlock transactions without actually seeing burn transaction in cosmos.network (to unlock big value of ETH). How this situation can be handled?

**Comment by fedekunze** [comment]
outdated
