### ISSUE TITLE
Showing ERROR: exit status 127 while executing $ ebrelayer generate

### ISSUE THREAD

**Issue by SudeshGagare** [cosmos/peggy#205]
### cosmos@ubuntu:~/go/src/github.com/cosmos/peggy-master/testnet-contracts$ ebrelayer generate
ERROR: exit status 127
cosmos@ubuntu:~/go/src/github.com/cosmos/peggy-master/testnet-contracts$

**Comment by SudeshGagare** [comment]
I have installed both solc and abigen globally, but still it is showing the same ERROR:exit status 127

**Comment by shanev** [comment]
Make sure it’s version 5 of solc. Current contracts aren’t compatible with v6.

**Comment by SudeshGagare** [comment]
How to install a specific version of Solc?? Because the Command "$ sudo snap install solc"  installs a different version.

**Comment by liu-zhipeng** [comment]
Hello, SudeshGagare!
You can install specific version of Solc using npm.
npm install -g solc@0.5.0

Thanks

**Comment by liu-zhipeng** [comment]
I have met same ERROR:exit status 127. 
I have installed solc 0.5.0 correctly.
How should I fix that ?
