### ISSUE TITLE
ebrelayer generate ERROR: exit status 1

### ISSUE THREAD

**Issue by trinhtan** [cosmos/peggy#222]
I run `ebrelayer generate` and it throws "ERROR: exit status 1"

**Comment by liu-zhipeng** [comment]
Hi, trinhtan.
I have met same error. 
Have you fixed that issue?

**Comment by himankgupta31** [comment]
Hi
I am also getting the same error.

Any luck.
Please help me if anyone knows.

**Comment by trinhtan** [comment]
I have fixed this problem. This is solc version problem, or path in `ebrelayer generate`. 
See my repo in 'ropsten' branch https://github.com/trinhtan/peggy/tree/ropsten. Note cmd/ebrelayer/contract/generator.go, please

**Comment by himankgupta31** [comment]
Hi 
Thanks for your reply.
I am using solc veriosn 0.5.12+commit.7709ece9.Linux.g++
Geth Version: 1.9.12-stable 

Which version are you using?

**Comment by trinhtan** [comment]
https://github.com/trinhtan/peggy/blob/ropsten/cmd/ebrelayer/contract/generator.go
see my file cmd/ebrelayer/contract/generator. I have changed a bit of BaseBindingGenCmd and GenerateBindings function to generates right path `bindings/bridgebank/BridgeBank.go` such as.

**Comment by himankgupta31** [comment]
Thanks
I can able to fix it.

**Comment by himankgupta31** [comment]
@trinhtan 

I could not able to run yarn commands. Even I deployed the contracts on local chain using truffle migrate command.

But for sending assets from Ethereum to COSMOS we need to use "yarn peggy:lock --default" but even though I have installed yarn but I could not able to run above command.

Please help

**Comment by himankgupta31** [comment]
Can anybody help me?
