### ISSUE TITLE
Upgradeable contracts

### ISSUE THREAD

**Issue by sunnya97** [cosmos/peggy#34]
We need to natively build in a mechanism to upgrade the peggy contracts on Ethereum in order to add features in the future (and potentially but really really hopefully not solve bug fixes).  Normally building Ethereum upgradeable contracts is a weird concept because its often unclear who should have the right to upgrade a Dapp, but in the case of Peggy, it seems that the current validator set should be able to upgrade it.

Some resources on upgradable contracts:  https://sunnya97.gitbooks.io/a-beginner-s-guide-to-ethereum-and-dapp-developme/content/upgradable-contracts.html

Building upgradeable contracts is not easy and I don't there are that many solidity devs with experience building them.  You'd have to complicated delegatecalls and stuff like that and we'd like to avoid a Parity bug like situation

**Comment by veqtor** [comment]
This would be a good pattern to follow:
https://blog.zeppelin.solutions/proxy-libraries-in-solidity-79fbe4b970fd

**Comment by 0v1se** [comment]
FYI, my implementation of upgradeable contracts: https://github.com/daonomic/contracts-upgradeable
With some tests
