### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by deuszx** [cosmos/peggy#391]
Hey Gravity team,

I would like to ask what's the status of the project? I can see last issue created around a month ago and the last PR merged even further back than that. Is the Gravity Bridge still being developed or was the project abandoned? 

Thanks

**Comment by sunnya97** [comment]
Development has moved to this repo:  https://github.com/Gravity-Bridge/Gravity-Bridge

**Comment by deuszx** [comment]
Thank you for the response @sunnya97 .
