### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by TanNgocDo** [cosmos/peggy#45]
Hi,
I see there is no new update for 9 months. Will it be continue in near future ?

**Comment by micahaza** [comment]
Would be nice to have some update for sure. Do you need any help, guys?

**Comment by ebuchman** [comment]
We will pick up work again on this in early 2019. Currently focused in on Cosmos-SDK and Tendermint so we can launch the Cosmos Hub.

**Comment by micahaza** [comment]
Great, let me know if you need testers or any kind of help.

**Comment by zramsay** [comment]
The repo is being revived by Swishlabs, see [this announcement](https://medium.com/thorchain/building-the-next-generation-bridge-870aeff16672) and [this PR](https://github.com/cosmos/peggy/pull/50). Stay tuned for an updated README and more information
