### ISSUE TITLE
Update to use new Module an Sdk conventions

### ISSUE THREAD

**Issue by musnit** [cosmos/peggy#52]
The project was started before various new SDK APIs and conventions emerged. The next phase should update the code to use these new APIs and conventions. Various small things can be changed to fit newer cosmos module conventions:
 - the way keepers are stored in the ethereumBridgeApp struct
 - use the new supply module
 - Use new module generalization allows you to register the modules easily. eg: in the SDK simapp/app.go
 - remove need for Genesis.go
 - use param functionality for the consensusNeeded field
 - can use new validator.IsBonded() in keeper.go
 - further suggestions from https://github.com/cosmos/cosmos-sdk/blob/master/docs/modules/SPEC.md
 - put querier into Keeper module
 - return Events from handler appropriately based on new Events paradigm rather than Tags
 - switch to go.mod
 - use new  account receiver in txs/relay.go
 - update to latest version of sdk and remove dependency on https://github.com/swishlabsco/crypto
 - change staking.Keeper to an interface that exposes only the methods used by this module
 - can use new sdk.NewCoins() in parser.go
 - add checks from https://github.com/cosmos/peggy/pull/51#discussion_r300800325
 - use module level cdc structure, ie: https://github.com/cosmos/peggy/pull/51#discussion_r300800973

**Comment by denalimarsh** [comment]
https://github.com/cosmos/peggy/pull/51#discussion_r300472621 requests ```sdk.NewCoins()``` which is included in this issue.

**Comment by musnit** [comment]
fixed in above
