### ISSUE TITLE
Relayer finality threshold of n blocks

### ISSUE THREAD

**Issue by denalimarsh** [cosmos/peggy#56]
The Relayer should enforce a finality threshold of n blocks so that witnessed events are probabilistically deterministic. The proposed implementation is a finality queue which enforces a 6 block finality threshold on witnessed events before allowing validators to sign them. This event persister can be expanded to a Relayer service which scans the blockchain for missed transactions upon initialization.

Thanks for creating this! I like the design you guys chose. Is there a finality check in the Relayer code? `Relayer` should have some `finalityBound` parameter so that it waits `finalityBound` number of blocks after seeing an event before creating an EthBridgeClaims. This mitigates risk that Etheruem re-orgs from causing peggy state to be invalid.

_Originally posted by @AdityaSripal in https://github.com/cosmos/peggy/pull/51#issuecomment-507412366_

**Comment by denalimarsh** [comment]
The finality threshold should be subject to tendermint consensus, meaning that this issue requires creating a new finality module. This will also allow each validator's state (active, inactive) to be confirmed each block.

**Comment by musnit** [comment]
@denalimarsh not sure what you mean exactly by this/by finality threshold requires tendermint consensus
