### ISSUE TITLE
production Level 

### ISSUE THREAD

**Issue by yash-fb** [cosmos/peggy#61]
which modules should we modify or pay attention to bring Peggy to the production level?
why do you mention that Peggy is not of production level, is it due to the lack of security or efficiency?
Basically, what are the functionalities that the Peggy currently lack and make it unsuitable for the production?

**Comment by jackzampolin** [comment]
@yash-fb would love to speak to you about this. Shoot me an email: jack [at] tendermint [dot] com

**Comment by JakeHartnell** [comment]
There are a bunch of people seeking the answer to this question. Is there some sort of roadmap we can look at?

Me and a few friends are curious as to what needs to be done to make this happen. : )
