### ISSUE TITLE
Issues with the upgraded version 

### ISSUE THREAD

**Issue by yash-fb** [cosmos/peggy#73]

**Comment by yash-fb** [comment]
The relayer is not able to catch the event.

**Comment by musnit** [comment]
@yash-fb This is fixed in upcoming PRs. They should all be merged within a week or two.

**Comment by yash-fb** [comment]
@musnit  one more thing is a bit confusing, from Readme you have removed the step of making a Validator before running a relayer isn't it like that a validator can only generate a claim?

**Comment by musnit** [comment]
@yash-fb in the current updated version validators are created during genesis and automatically staked, so don't need to be added.

Note that this peggy app is just a demo app for the cosmos sdk that uses the peggy modules with 1 validator setup, and is not intended to be run as it's own chain. The peggy modules can be included in any other chain that has its own setup regarding validators.
