### ISSUE TITLE
Automatic claim processing when detects a lock event

### ISSUE THREAD

**Issue by Arunhfb** [cosmos/peggy#80]
In automatic claim processing the relayer is not able to detect the events and performs a succesfull transation.
Since i tried transferring the tokens from remix i didnt received any output from relayer but the transaction was successful but when i checked the receiver account there was no update in the account .

**Comment by musnit** [comment]
@Arunhfb the code you are using is old and no longer supported. It is being replaced by upcoming new code in the Pull Requests that will be merged in the next 3 weeks.
