### ISSUE TITLE
Discussion - Add id to prophecies?

### ISSUE THREAD

**Issue by musnit** [cosmos/peggy#92]
The rest client interface requires a  lot of paramaters to query a prophecy, so means an annoying time making the request:
```
	r.HandleFunc(fmt.Sprintf("/%s/prophecies/{%s}/{%s}/{%s}/{%s}/{%s}/{%s}", storeName, restEthereumChainID, restBridgeContract, restNonce, restSymbol, restTokenContract, restEthereumSender), getProphecyHandler(cliCtx, storeName)).Methods("GET")
```

This could be improved by adding an id to the prophecy object and allow for querying just by id. This probably makes sense, though should be thought through more - there are a bunch of implications of adding ids, like:
 - more space used
 - doesn't improve UX for end users at all really, only devEX for developers building ontop of peggy, which is a minor efficiency difference anyway. End users will likely eventually interact with these systems through some frontend/UI/dapp, where the chainid/contract/nonce/etc will likely be either hardcoded, or selectable in a dropdown, or remembered from previous usage.
 - having an id and endpoint based on id means that prophecies can no longer be retrieved easily by deterministically working out the url based on what original request they got triggered by, and there are likely some consumers based that need this characteristic. we can of course still leave this compound-key endpoint in, in addition to adding a single-key id endpoint, so that those needs are still met
 - clients/fat web apps that are built in future consuming this UI now also may need to keep track of ids, and the id will be generated server(blockchain) side and so they need to get it from the server
 - most transactions/requests will likely come in asynchronously, where it is not possible to return the id in that request, so consumers will need to do a second query later on, or wait for transaction confirmation until they get the id back and know what it is.

anyway, as mentioned, we could also have both query endpoints in so may make sense to go ahead with adding ids

**Comment by denalimarsh** [comment]
I think it makes sense to add a prophecy ID to simplify things, as devEX is crucial in getting Peggy integrated into user facing applications. This is also closer to what we're doing with the prophecy ID on the Ethereum side. In order to generate/store the ID on the server (blockchain), will there be an additional Msg similar to the `LogNewProphecyClaim` event?

**Comment by musnit** [comment]
Yep agree.  My above points signal that it could make devX worse for some use cases /integrations though, so should think about it in terms of how consumers will use it more and then make a decision

**Comment by fedekunze** [comment]
See the governance module. All proposals contain a proposal Id. 

Another benefit of implementing this is that it reduces the size of the key to access the value on the KVStore
