### ISSUE TITLE
create validator  ebcli command not working

### ISSUE THREAD

**Issue by Arunhfb** [cosmos/peggy#96]
I am having a testuser i want to make him validator.
I have used the command mentioned in Image-1.The command is showing the output successfully but when i am checking the staking validators its showing me the default one provided at time of creating the genensis.
![Image-2](https://user-images.githubusercontent.com/52598934/68649984-f2a6f180-0549-11ea-9acb-dda617f25e1e.png)
![Image-1](https://user-images.githubusercontent.com/52598934/68649985-f2a6f180-0549-11ea-9278-5b14d0cc69be.png)

**Comment by njmurarka** [comment]
I think we got stuck in a similar place. Did you copy over the genesis file to every validator?
